---
title: "Yellow Tail GLORY & MOM6"
output: html_notebook
---

```{r packages}
library(dplyr)
library(ggplot2)
library(tidyverse)
```


```{r clear environment}
rm(list = ls())
```


```{r read in Glory Yellow Tail Data}
Full_Glory_Yellow_Tail.df <- read.csv("2024Env-annual-yellowtail_GLORYS_UNSTANDARDIZED.csv")
head(Full_Glory_Yellow_Tail.df)
```

```{r}
###Dat
###Pivot Longer(names_to, variable)
### Use variables that MOM6 and Glory have together
```


```{r}
Yt_temp <- Full_Glory_Yellow_Tail.df %>% filter(year >= 2010 & year <= 2020) %>%

select(year, DDegg)

head(Yt_temp)

```

```{r Year/Temp Plot}
Yt_temp %>%
  ggplot(aes(x = year, y = DDegg)) +
  geom_point() + 
  geom_line() +
  labs(title = "Temp over the Years", x = "Years", y = "Temp") + 
  theme_minimal() 
```
```{r Bring in MOM6 Data}
Full_MOM6_Yellow_Tail.df <- read.csv("yellowtail_MOM6.csv")

head(Full_MOM6_Yellow_Tail.df)
```

```{r Filter GLORY Variables}

Filtered_Glory_Yellow_Tail.df <- Full_Glory_Yellow_Tail.df %>% select(year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv, CSTlarv, CSTpjuv, LSTlarv, LSTpjuv)


```

```{r}
GYL_datalong <- Filtered_Glory_Yellow_Tail.df %>%
  pivot_longer(
    cols = c(year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv, CSTlarv, CSTpjuv, LSTlarv, LSTpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "GLORYs")


```


###How do I fix the years in these??? Showing up as long exponents

```{r Filter MOM6 Variables }

Filtered_MOM6_Yellow_Tail.df <- Full_MOM6_Yellow_Tail.df%>% select(year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv,XVlarv, XVpjuv, YVlarv, YVpjuv)

```

```{r}
MOM6YL_datalong <- Filtered_MOM6_Yellow_Tail.df %>%
  pivot_longer(
    cols = c(year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv,XVlarv, XVpjuv, YVlarv, YVpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "MOM6")
```





```{r Combine Datasets}

###Question would it be better for me to rename the coulmn names to be the same so I can merge them or?

```

