---
title: "PetraleSole ROMs vs. GLORY"
output: html_notebook
---


```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(here) 
library(patchwork)
```

```{r clear environment}
rm(list = ls())
```


###GLORY PetraleSole Data wrangling

```{r read in GLORY PetraloeSole Data}

Full_Glory_Petrale.df <- read.csv(
  here("Data","PetraleSole","DATA_Combined_glorys_petrale.csv")
)

head(Full_Glory_Petrale.df)

```
```{r Filter GLORY Variables}

Filtered_Glory_Petrale.df <- Full_Glory_Petrale.df %>% select(year, DDpre, Tpre.a, Tpre.b, MLDegg, CSTegg1, DDegg1, CSTegg2, LSTegg2, DDegg2, LSTlarv,CSTlarv, DDlarv, LSTpjuv, CSTpjuv, DDpjuv, LSTbjuv.a, CSTbjuv.a, LSTbjuv.b, CSTbjuv.b )

head(Filtered_Glory_Petrale.df)

```

```{r Make GLORY data long}
Glory_Petrale_datalong <- Filtered_Glory_Petrale.df %>%
  pivot_longer(
    cols = c( DDpre, Tpre.a, Tpre.b, MLDegg, CSTegg1, DDegg1, CSTegg2, LSTegg2, DDegg2, LSTlarv,CSTlarv, DDlarv, LSTpjuv, CSTpjuv, DDpjuv, LSTbjuv.a, CSTbjuv.a, LSTbjuv.b, CSTbjuv.b ),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "GLORYs")

###LSTegg is listed on the Data Availabiliy document but there is no LSTegg column in csv file. there is an LSTegg 2 however

print(Glory_Petrale_datalong)

```

###ROMs PetraleSole data Wrangling


```{r read in ROMs PetraloeSole Data}

Full_ROMs_Petrale.df <- read.csv(
  here("Data","PetraleSole","Petrale-ROMS-data.csv")
)

head(Full_ROMs_Petrale.df)

```

```{r Filter ROMs Variables}

Filtered_ROMs_Petrale.df <- Full_ROMs_Petrale.df %>% select(year, DDpre, Tpre.a, Tpre.b, MLDegg, CSTegg1, DDegg1, CSTegg2, LSTegg2, DDegg2, LSTlarv,CSTlarv, DDlarv, LSTpjuv, CSTpjuv, DDpjuv, LSTbjuv.a, CSTbjuv.a, LSTbjuv.b, CSTbjuv.b ) %>% 
  
  filter(year >= 1993 & year <= 2023) ### Matches ROMs years to the years GLORY dataset had

head(Filtered_ROMs_Petrale.df)

```

```{r Make ROMs data long}
ROMs_Petrale_datalong <- Filtered_ROMs_Petrale.df %>%
  pivot_longer(
    cols = c( DDpre, Tpre.a, Tpre.b, MLDegg, CSTegg1, DDegg1, CSTegg2, LSTegg2, DDegg2, LSTlarv,CSTlarv, DDlarv, LSTpjuv, CSTpjuv, DDpjuv, LSTbjuv.a, CSTbjuv.a, LSTbjuv.b, CSTbjuv.b ),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "ROMs")

###LSTegg is listed on the Data Availability document but there is no LSTegg column in csv file, there is an LSTegg 2 however (whats the difference??)

print(ROMs_Petrale_datalong)

```

```{r Combining Datasets}

combined_models <- rbind(ROMs_Petrale_datalong, Glory_Petrale_datalong)

head(combined_models)

```


```{r Tpre.a Plot, echo=FALSE, message=FALSE, warning=FALSE}

combined_models %>%
  filter(variable == "Tpre.a") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "Temporal Comparison of Temperature Cues for pre-conditioning (Tpre.a)\nin PetraleSole: GLORYS vs ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))
```

```{r GLORY Data Pre 2010}
Pre2010_GLORY_Petrale <- Glory_Petrale_datalong %>% 
  filter(year >= 1993 & year <= 2010) %>%

print(Pre2010_GLORY_Petrale)

```

```{r GLORY Data Post 2010}
Post2010_GLORY_Petrale <- Glory_Petrale_datalong %>% 
  filter(year >= 2010 & year <= 2023) %>%

print(Post2010_GLORY_Petrale)

```
```{r ROMs Data Pre 2010}
Pre2010_ROMs_Petrale <- ROMs_Petrale_datalong %>% 
  filter(year >= 1993 & year <= 2010) %>%

print(Pre2010_ROMs_Petrale)

```

```{r ROMs Data post 2010}
Post2010_ROMs_Petrale <- ROMs_Petrale_datalong %>% 
  filter(year >= 2010 & year <= 2023) %>%

print(Post2010_ROMs_Petrale)

```


```{r Combining Pre 2010 Datasets}

pre2010_combined_models <- rbind(Pre2010_GLORY_Petrale, Pre2010_ROMs_Petrale)

head(combined_models)

```


```{r Combining Post 2010 Datasets}

post2010_combined_models <- rbind(Post2010_ROMs_Petrale, Post2010_GLORY_Petrale)

head(combined_models)

```

```{r Pre-2010 Tpre.a Plot, echo=FALSE, message=FALSE, warning=FALSE}

pre2010_combined_models %>%
  filter(variable == "Tpre.a") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 2 )) +
  labs(title = "Pre-2010 Temporal Comparison of pre-conditioning (Tpre.a)\nin PetraleSole: GLORYS vs ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

```

```{r Post-2010 Tpre.a Plot, echo=FALSE, message=FALSE, warning=FALSE}

post2010_combined_models %>%
  filter(variable == "Tpre.a") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 2 )) +
  labs(title = "Post-2010 Temporal Comparison of pre-conditioning (Tpre.a)\nin PetraleSole: GLORYS vs ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

```


```{r Tpre.a Plot all years, echo=FALSE, message=FALSE, warning=FALSE}

combined_models %>%
  filter(variable == "Tpre.a") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "Temporal Comparison of pre-conditioning (Tpre.a)\nin PetraleSole: GLORYS vs ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

```

```{r Pre-2010 Facet Wrap PetraleSole, echo=FALSE, message=FALSE, warning=FALSE}
pre2010_combined_models %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 10 )) +
  facet_wrap(~variable, scales = "free_y")+
labs( color = ("Ocean Model")) + ggtitle("Pre-2010 Oceanographic Variables",
          subtitle = "Northern Yellowtail: GLORYS vs MOM6") +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10)
  )


###Major differences between the all the Degree Day Values
```

```{r Degree Day Variables (DD) Facet Wrap PetraleSole, echo=FALSE, message=FALSE, warning=FALSE}

combined_models %>%
   filter(variable %in% c("DDegg1", "DDegg2", "DDlarv", "DDpjuv", "DDpre")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 10 )) +
  facet_wrap(~variable, scales = "free_y")+
labs( color = ("Ocean Model")) + ggtitle("Degree Day Oceanographic Variables",
          subtitle = "PetraleSole: GLORYS vs MOM6") +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10)
  )


###Major differences between the all the Degree Day Values
```




```{r DDEgg all years, echo=FALSE, message=FALSE, warning=FALSE}

combined_models %>%
  filter(variable == "DDegg1") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "Temporal Comparison of DDegg \nin PetraleSole: GLORYS vs ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

```

```{r ROMS DDegg1 , echo=FALSE, message=FALSE, warning=FALSE}

ROMs_Petrale_datalong %>%
  filter(variable == "DDegg1") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "DDEgg 1 PetraleSole ROMs",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

```
```{r DDegg1 Plot all years, echo=FALSE, message=FALSE, warning=FALSE}

ddegg11 <- Glory_Petrale_datalong %>%
  filter(variable == "DDegg1") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
   scale_color_manual(values = c("GLORYs" = "slateblue"))+
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "DDegg1 of PetraleSole: GLORYS",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))


ddegg12 <- ROMs_Petrale_datalong %>%
  filter(variable == "DDegg1") %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
    scale_color_manual(values = c("ROMs" = "indianred2"))+
  scale_x_continuous(breaks = seq(min(combined_models$year), max(combined_models$year), by = 5 )) +
  labs(title = "DDegg1 of PetraleSole: ROMS",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Ocean Model"))

ddegg11 / ddegg12

###Are they in different units by chance??
###Explanation of DDEgg...(Is it the temp of water during the egg cycle?)


```


