---
title: "Yellow Tail GLORY vs. MOM6"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,      # hides the code
  warning = FALSE,   # hides warnings
  message = FALSE    # hides messages
)
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(here) 
library(patchwork)
library(standardize)
library(ggpubr)
library(gridExtra)
library(data.table) 
library(lubridate)
library(corrplot)
library(mgcv)
library(tidync)
library(gratia)
```

```{r clear environment}
rm(list = ls())
```

```{r}
system("git clone https://github.com/mfeddern/OceanModelIndexComparison.git")
```
```{r}
setwd("OceanModelIndexComparison")
system("git pull origin main")  # or replace 'main' with the correct branch

```


###Wrangling GLORY Data

```{r read in Glory Yellow Tail Data}

Full_Glory_Yellow_Tail.df <- read.csv(
  here("Data","Yellowtail","2024Env-annual-yellowtail_GLORYS_UNSTANDARDIZED.csv")
)

Full_Glory_Yellow_Tail.df <- na.omit(Full_Glory_Yellow_Tail.df) 


```


```{r Filter out Variables}
Full_Glory_Yellow_Tail.df <- Full_Glory_Yellow_Tail.df %>%
  select(year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv, CSTlarv, CSTpjuv, LSTlarv, LSTpjuv)%>%
  mutate(source = "GLORY")

head(Full_Glory_Yellow_Tail.df)
  
```




```{r Unscaled Data}

UnScaled_Filtered_Glory_Yellow_Tail.df <- Full_Glory_Yellow_Tail.df %>%
  mutate(scaled = FALSE)

head(UnScaled_Filtered_Glory_Yellow_Tail.df)

```


```{r Scaling GLORY Data}

Scaled_Filtered_Glory_Yellow_Tail.df <-  Full_Glory_Yellow_Tail.df %>%
  mutate_at(c('Tcop', 'Tpart', 'MLDpart', 'MLDlarv', 'MLDpjuv', 'CSTlarv', 'CSTpjuv', 'LSTlarv', 'LSTpjuv'), ~(scale(.) %>% as.vector)) %>%
  mutate(scaled = TRUE)

head(Scaled_Filtered_Glory_Yellow_Tail.df)

```

```{r}
apply(Scaled_Filtered_Glory_Yellow_Tail.df, 2, mean)

```


```{r}
apply(Scaled_Filtered_Glory_Yellow_Tail.df, 2, sd)
```


```{r Make UnScaled GLORY data long}
UnScaled_GYL_datalong <- UnScaled_Filtered_Glory_Yellow_Tail.df %>%
  pivot_longer(
    cols = c( Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv, CSTlarv, CSTpjuv, LSTlarv, LSTpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "GLORYs")

print(UnScaled_GYL_datalong)

```

```{r Make Scaled GLORY data long}

Scaled_GYL_datalong <- Scaled_Filtered_Glory_Yellow_Tail.df %>%
  pivot_longer(
    cols = c( Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv, CSTlarv, CSTpjuv, LSTlarv, LSTpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "GLORYs")

print(Scaled_GYL_datalong)

```

```{r}
Glory_combined.df <- bind_rows(Scaled_GYL_datalong, UnScaled_GYL_datalong )

head(Glory_combined.df)

```
```{r GLORYs Scaled vs. Unscaled}

Glory_combined.df %>%
  filter(variable == "Tcop") %>%
  ggplot(aes(x = year, y = value, color = scaled)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(Glory_combined.df$year), max(Glory_combined.df$year), by = 3 )) +
  labs(title = "Temporal Comparison of Scaled and Unscaled Temperature Cues for Copulation\n(Tcop) in Northern Yellowtail: GLORYS",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Scaled"))

```


###Wrangling MOM6 Data

```{r Bring in MOM6 Data}
Full_MOM6_Yellow_Tail.df <- read.csv(
  here("Data", "Yellowtail", "yellowtail_MOM6.csv"))



head(Full_MOM6_Yellow_Tail.df)
```

```{r}
Full_MOM6_Yellow_Tail.df <- Full_MOM6_Yellow_Tail.df %>%
  select(
    year, Tcop, Tpart, MLDpart, MLDlarv, MLDpjuv,
    XVlarv, XVpjuv, YVlarv, YVpjuv
  ) %>%
  mutate(source = "MOM6") %>%
  rename(
    CSTlarv = XVlarv,
    CSTpjuv = XVpjuv,
    LSTlarv = YVlarv,
    LSTpjuv = YVpjuv
  ) %>%
  filter(year >= 1998 & year <= 2021) %>%   # Match GLORY's year range
  na.omit()  # Remove rows with any NAs

print(Full_MOM6_Yellow_Tail.df)
```


```{r Scaling MOM6 Data}

Scaled_MOM6_Yellow_Tail.df <- Full_MOM6_Yellow_Tail.df %>%
  mutate_at(c('Tcop', 'Tpart', 'MLDpart', 'MLDlarv', 'MLDpjuv', 'CSTlarv', 'CSTpjuv', 'LSTlarv', 'LSTpjuv'), ~(scale(.) %>% as.vector)) %>%
  mutate(scaled = TRUE)


head(Scaled_MOM6_Yellow_Tail.df)


```

```{r}
apply(Scaled_MOM6_Yellow_Tail.df, 2, sd)
```

```{r}
apply(Scaled_MOM6_Yellow_Tail.df, 2, mean)
```

```{r Make Unscaled MOM6 data long}

Unscaled_MOM6YL_datalong <- Full_MOM6_Yellow_Tail.df %>%
  pivot_longer(
    cols = c( Tcop, Tpart, MLDpart,MLDlarv, MLDpjuv, CSTlarv, CSTpjuv,LSTlarv, LSTpjuv, LSTlarv, LSTpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(source = "MOM6") %>%
mutate(scaled = FALSE)


print(Unscaled_MOM6YL_datalong)
```

```{r Make Scaled MOM6 data long}

Scaled_MOM6YL_datalong <- Scaled_MOM6_Yellow_Tail.df %>%
  pivot_longer(
    cols = c( Tcop, Tpart, MLDpart,MLDlarv, MLDpjuv, CSTlarv, CSTpjuv,LSTlarv, LSTpjuv, LSTlarv, LSTpjuv),
    names_to = "variable",
    values_to = "value"
  ) %>%
   mutate(source = "MOM6") %>%
mutate(scaled = TRUE)

print(Scaled_MOM6YL_datalong)
```


```{r Combining MOM6 Datasets}

MOM6_combined_models <- rbind(Scaled_MOM6YL_datalong,Unscaled_MOM6YL_datalong)

head(MOM6_combined_models)

```

```{r MOM6 Scaled vs. Unscaled}

MOM6_combined_models %>%
  filter(variable == "Tcop") %>%
  ggplot(aes(x = year, y = value, color = scaled)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(MOM6_combined_models$year), max(MOM6_combined_models$year), by = 3 )) +
  labs(title = "Temporal Comparison of Scaled and Unscaled Temperature Cues for Copulation\n(Tcop) in Northern Yellowtail: MOM6",
       y = ("Temperature (°C)"),
       x = ("Year"),
       color = ("Scaled"))

```



```{r Scaled Combining Datasets}

Scaled_combined_models <- rbind(Scaled_GYL_datalong, Scaled_MOM6YL_datalong)

head(Scaled_combined_models)

```


```{r UnScaled Combining Datasets}

UnScaled_combined_models <- rbind(UnScaled_GYL_datalong, Unscaled_MOM6YL_datalong)

head(UnScaled_combined_models)

```

```{r Example Function}

my_function <- function(variable_name,dataframe, plot_title, y_axis) {

dataframe %>%
  filter(variable == variable_name) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 3 )) +
  labs(title = plot_title,
       y = y_axis,
       x = ("Year"),
       color = ("Ocean Model"))
}
  
  
  
```

```{r Scaled Tcop Graphs}
my_function("Tcop",Scaled_combined_models,"Scaled Temporal Comparison of Temperature Cues for Co-Population (Tcop)\nin Northern Yellowtail: GLORYS vs MOM6","Temperature (°C)")


```
```{r UnScaled Tcop Graphs}
my_function("Tcop",UnScaled_combined_models,"Unscaled Temporal Comparison of Temperature Cues for Co-Population (Tcop)\nin Northern Yellowtail: GLORYS vs MOM6","Temperature (°C)")


```

```{r example linear model}

###Waiting for CSV file with the recruitment values

###model = lm(y_rec~ value , data = Scaled_combined_models) #Create the linear regression
###summary(model)


```



```{r FacetWrap Plot Function}

### variable_name is a vector of strings that refer to column names in the dataframe

FacetWrap_function <- function(variable_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(variable %in% variable_name) %>%
    ggplot(aes(x = year, y = value, color = source)) +
    geom_point() +
    geom_line() +
    geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    facet_wrap(~variable, scales = "free_y") +
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(
      title = plot_title,
      y = y_axis,
      x = "Year",
      color = "Source"
    ) +
    theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))
}
  
  
  
```


```{r}

FacetWrap_function(
  variable_name = c("Tcop", "Tpart"),
  dataframe = Scaled_GYL_datalong,
  plot_title = "Temperature Trends (Long Format)",
  y_axis = "Scaled Value"
)



```

`


```{r}

FacetWrap_function(
  variable = c("Tcop", "Tpart"),
  dataframe = Scaled_combined_models,
  plot_title = "Temperature Trends - GLORY",
  y_axis = "Scaled Value"
)

```



```{r Facet Wrap Scaled plots, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=8}

Scaled_combined_models %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 10 )) +
  facet_wrap(~variable, scales = "free_y")+
labs( color = ("Ocean Model"))


```


```{r}

# Get a list of variables
plot_list <- Scaled_combined_models %>%
  split(.$variable) %>%
  lapply(function(df) {
    ggplot(df, aes(x = year, y = value, color = source)) +
      geom_point() + 
      geom_line() + 
      scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 10)) +
      labs(title = unique(df$variable), color = "Ocean Model") +
      theme_minimal()
  })

```


```{r}
ggarrange(
  plotlist = plot_list,
  ncol = 2,
  labels = NULL,  # Disable extra labels
  align = "hv",
  common.legend = TRUE,
  legend = "bottom",
  widths = 1,
  font.label = list(size = 12, face = "plain")  # Simplify
)


```


```{r}

make_plot <- function(var_name) {
  df <- filter(Scaled_combined_models, variable == var_name)
  
  ggplot(df, aes(x = year, y = value, color = source)) +
    geom_point() +
    geom_line() +
    geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    labs(title = var_name, color = "Ocean Model") +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 5)) +
    theme_bw() +
    theme(
      panel.spacing = unit(1, "lines"),
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
    )
}



# Create individual plots
LSTPjuv <- make_plot("LSTpjuv")
LSTlarv <- make_plot("LSTlarv")
CSTpjuv <- make_plot("CSTpjuv")
CSTlarv <- make_plot("CSTlarv")
Tpart <- make_plot("Tpart")
Tcop <- make_plot("Tcop")
MLDlarv <- make_plot("MLDlarv")
MLDpjuv <- make_plot("MLDpjuv")
MLDpart <- make_plot("MLDpart")


```



```{r}
# Use correct variable names (case-sensitive!)
vars <- c("LSTpjuv", "LSTlarv", "CSTpjuv", "CSTlarv", 
          "Tpart", "Tcop", "MLDlarv", "MLDpjuv", "MLDpart")


# Create styled plot list
plot_list <- lapply(vars, make_plot)

# Arrange plots in 3×3 grid
all_variables_plot <- ggarrange(
  plotlist = plot_list,
  ncol = 3,
  nrow = 3,
  labels = LETTERS[1:length(plot_list)],
  font.label = list(size = 12, face = "bold"),
  align = "hv",
  common.legend = TRUE,
  legend = "bottom"
)

# Add single axis labels
annotate_figure(
  all_variables_plot,
  left = text_grob("Standardized values", rot = 90, size = 14),
  bottom = text_grob("Year", size = 14)
)


print (all_variables_plot)
```



```{r}

# Save to PNG
ggsave("standardized_comparison_grid.png", plot = all_variables_plot, width = 12, height = 10, dpi = 300)

```


```{r}

FacetWrap_function(
  variable = c("CSTlarv", "CSTpjuv"),
  dataframe = Scaled_combined_models,
  plot_title = "Cross Shelf Transport - GLORY",
  y_axis = "Scaled Value"
)

```



```{r Scaled CST plots, echo=FALSE, message=FALSE, warning=FALSE}

CST_ScaledPlots <- Scaled_combined_models %>%
  filter(variable %in% c("CSTlarv", "CSTpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c(
               "CSTlarv" = "Larval (CSTlarv)",
               "CSTpjuv" = "Pelagic Juvenile (CSTpjuv)"
             ))) +
  labs(
    color = "Ocean Model",
    title = "Scaled Comparison of Cross Shelf Transport (CST)\nfor Northern Yellowtail: GLORYS vs MOM6"
  ) +
  theme_bw() +  # Apply base theme first
  theme(
    plot.title = element_text(size = 16),  # Adjust as needed
    strip.text = element_text(size = 14, face = "bold"),
    strip.background = element_rect(fill = "lightblue", color = "grey"),
    panel.spacing = unit(1, "lines")
  )

print(CST_ScaledPlots)

```


```{r Unscaled CST plots, echo=FALSE, message=FALSE, warning=FALSE}

CST_UnScaledPlots <- UnScaled_combined_models %>%
  filter(variable %in% c("CSTlarv", "CSTpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
    scale_x_continuous(breaks = seq(min(UnScaled_combined_models$year), max(UnScaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("CSTlarv" = "Larval (CSTlarv)", "CSTpjuv" = "Pelagic Juvenile (CSTpjuv)"))) +
  labs(color = "Ocean Model") +
  labs(title = "UnScaled Comparison of Cross Shelf Transport (CST)\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))

print(CST_UnScaledPlots)

```


```{r Scaled LST Variables, echo=FALSE, message=FALSE, warning=FALSE}

Scaled_combined_models %>%
  filter(variable %in% c("LSTlarv", "LSTpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("LSTlarv" = "Larval (LSTlarv)", "LSTpjuv" = "Pelagic Juvenile (CSTpjuv)"))) +
  labs(color = "Ocean Model") +
  labs(title = "Scaled Comparison of Longshore Transport (LST)\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))
```


```{r Unscaled LST Variables, echo=FALSE, message=FALSE, warning=FALSE}

UnScaled_combined_models %>%
  filter(variable %in% c("LSTlarv", "LSTpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("LSTlarv" = "Larval (LSTlarv)", "LSTpjuv" = "Pelagic Juvenile (CSTpjuv)"))) +
  labs(color = "Ocean Model") +
  labs(title = "UnScaled Comparison of Longshore Transport (LST)\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))
```


```{r  Scaled Temperature Variables}

Scaled_combined_models %>%
  filter(variable %in% c("Tcop", "Tpart")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("Tcop" = "Copulation (Tcop)", "Tpart" = "Parturition (Tpart)"))) +
  labs(color = "Ocean Model") +
  labs(title = "Scaled Comparison of Temperature\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))
```

```{r UnScaled Temperature Variables}

UnScaled_combined_models %>%
  filter(variable %in% c("Tcop", "Tpart")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(UnScaled_combined_models$year), max(UnScaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("Tcop" = "Copulation (Tcop)", "Tpart" = "Parturition (Tpart)"))) +
  labs(color = "Ocean Model") +
  labs(title = "Unscaled Comparison of Temperature\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))

```




```{r Scaled MLD plots}

MLD_Plots <- Scaled_combined_models %>%
  filter(variable %in% c("MLDlarv", "MLDpart", "MLDpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
  scale_x_continuous(breaks = seq(min(Scaled_combined_models$year), max(Scaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c(
               "MLDlarv" = "Larval (MLDlarv)", 
               "MLDpart" = "Parturition (MLDpart)", 
               "MLDpjuv" = "Pelagic Juvenile (MLDpjuv)"
             ))) +
  labs(color = "Ocean Model",
       title = "Scaled Comparison of Mixed Layer Depth (MLD)\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +  
  theme(
    plot.title = element_text(size = 16),
    strip.text = element_text(size = 14, face = "bold"),
    strip.background = element_rect(fill = "lightblue", color = "grey"),
    panel.spacing = unit(1, "lines")
  )

print(MLD_Plots)

```
```{r}
# Save to PNG
ggsave("standardized_MLD_grid.png", plot = MLD_Plots, width = 12, height = 10, dpi = 300)
```


```{r Unscaled MLD variables}

UnScaled_combined_models %>%
  filter(variable %in% c("MLDlarv", "MLDpart", "MLDpjuv")) %>%
  ggplot(aes(x = year, y = value, color = source)) +
  geom_point() + 
  geom_line() + 
  scale_x_continuous(breaks = seq(min(UnScaled_combined_models$year), max(UnScaled_combined_models$year), by = 4)) +
  facet_wrap(~variable, scales = "free_y", ncol = 1, 
             labeller = labeller(variable = c("MLDlarv" = "Larval (MLDlarv)", "MLDpart" = "Parturition (MLDpart)", "MLDpjuv" = "Pelagic Juvenile (MLDpjuv)"))) +
  labs(color = "Ocean Model") +
  labs(title = "Unscaled Comparison of Mixed Layer Depth (MLD)\nfor Northern Yellowtail: GLORYS vs MOM6") +
  theme_bw() +
  theme(strip.text = element_text(size = 12, face = "bold"),
        strip.background = element_rect(fill = "lightblue", color = "grey"),
        panel.spacing = unit(1, "lines"))
```


###Wrangling Monthly MOM6 Data

```{r Bring in Monthly MOM6 Data}
yellowtail_MOM6_monthly.df <- read.csv(
  here("Data","Yellowtail","yellowtail_MOM6_monthly.csv"))



head(yellowtail_MOM6_monthly.df)
```


```{r Filtering Years & Seaons}


season_MOM6_monthly.df  <- yellowtail_MOM6_monthly.df  %>%
  
filter(year >= 1998 & year <= 2021) %>% ###Matching the GLORY years 
  
 mutate(Season = case_when(
    month %in% 1:3 ~ "Winter",
    month %in% 4:6 ~ "Spring",
    month %in% 7:9 ~ "Summer",
    month %in% 10:12 ~ "Autumn",
    TRUE ~ NA_character_
  ))

head(season_MOM6_monthly.df)

```


```{r Make Monthly Unscaled MOM6 data long}

# Explicitly convert all pivot columns to numeric
cols_to_pivot <- c("MLD_90_180", "MLD_0_180", "MLD_0_90", "MLD_30_130", "MLD_180_550", 
                   "T_90_180", "T_0_180", "T_0_90", "T_30_130", "T_180_550", 
                   "XV_90_180", "XV_0_180", "XV_0_90", "XV_30_130", "XV_180_550", 
                   "YV_90_180", "YV_0_180", "YV_0_90", "YV_30_130", "YV_180_550")

# Ensure all those columns are numeric
season_MOM6_monthly.df <- season_MOM6_monthly.df %>%
  mutate(across(all_of(cols_to_pivot), ~ as.numeric(.)))

# Pivot longer safely
Unscaled_season_MOM6YL_datalong <- season_MOM6_monthly.df %>%
  pivot_longer(
    cols = all_of(cols_to_pivot),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(
    source = "MOM6",
    scaled = FALSE
  )


head(Unscaled_season_MOM6YL_datalong)

```




```{r Scaling Monthly MOM6 Data}

Scaled_season_MOM6_monthly.df <- season_MOM6_monthly.df %>%
  mutate_at(c('MLD_90_180', 'MLD_0_180', 'MLD_0_90', 'MLD_30_130', 'MLD_180_550', 'T_90_180', 'T_0_180', 'T_0_90', 'T_30_130','T_180_550','XV_90_180','XV_0_180', 'XV_0_90','XV_30_130','XV_180_550', 'YV_90_180', 'YV_0_180', 'YV_0_90', 'YV_30_130', 'YV_180_550' ), ~(scale(.) %>% as.vector)) %>%
  mutate(scaled = TRUE)

Scaled_season_MOM6_monthly.df <- na.omit(Scaled_season_MOM6_monthly.df )

head(Scaled_season_MOM6_monthly.df)


```

```{r}
apply(Scaled_season_MOM6_monthly.df, 2, sd)
```

```{r}
apply(Scaled_season_MOM6_monthly.df, 2, mean) 
```


```{r Make Monthly Scaled MOM6 data long}

library(scales)  


cols_to_scale <- c("MLD_90_180", "MLD_0_180", "MLD_0_90", "MLD_30_130", "MLD_180_550", 
                   "T_90_180", "T_0_180", "T_0_90", "T_30_130", "T_180_550", 
                   "XV_90_180", "XV_0_180", "XV_0_90", "XV_30_130", "XV_180_550", 
                   "YV_90_180", "YV_0_180", "YV_0_90", "YV_30_130", "YV_180_550")


# Step 1: Ensure numeric columns
season_MOM6_monthly.df <- season_MOM6_monthly.df %>%
  mutate(across(all_of(cols_to_scale), ~ as.numeric(.)))

# Step 2: Pivot longer
Scaled_season_MOM6YL_datalong <- season_MOM6_monthly.df %>%
  pivot_longer(
    cols = all_of(cols_to_scale),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(
    source = "MOM6",
    scaled = TRUE,
    Season = case_when(
      month %in% 1:3 ~ "Winter",
      month %in% 4:6 ~ "Spring",
      month %in% 7:9 ~ "Summer",
      month %in% 10:12 ~ "Autumn",
      TRUE ~ NA_character_
    )
  ) %>%
  group_by(variable, Season) %>%
  mutate(scaled_value = scale(value) %>% as.vector()) %>%
  mutate(value = scaled_value) %>%
  select(-scaled_value) %>%
  drop_na(value) %>%
  ungroup()



# Print for review
print(Scaled_season_MOM6YL_datalong)

```

```{r}
  Scaled_season_MOM6YL_datalong <- Scaled_season_MOM6YL_datalong %>%
    mutate(Season = case_when(
      Season == "Winter" ~ "Winter (Jan–Mar)",
      Season == "Spring" ~ "Spring (Apr–Jun)",
      Season == "Summer" ~ "Summer (Jul–Sep)",
      Season == "Autumn" ~ "Autumn (Oct–Dec)",
      TRUE ~ Season
    ))
```



```{r Combining Monthly MOM6 Datasets}

MOM6_monthlycombined_models <- rbind(
  Scaled_season_MOM6YL_datalong,
  Unscaled_season_MOM6YL_datalong
) %>%
  group_by(year, Season, variable, source, scaled) %>%
  summarise(value = mean(value, na.rm = TRUE), .groups = "drop")

head(MOM6_monthlycombined_models)

```
```{r All Season Plot Function}

MOM6all_seasonal_function <- function(variable_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(variable == variable_name) %>%
    group_by(year, Season, variable, scaled, source) %>%
    summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
    ggplot(aes(x = year, y = value, color = Season)) +
    geom_point() +  
    geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    geom_line() + 
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(title = plot_title,
         y = y_axis,
         x = "Year",
         color = "Season") +
    theme_minimal()
}



###Take means of each season so it plots mean of each season over each year
```


```{r}

MOM6plot_function_by_season <- function(variable_name, season_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(variable == variable_name, Season == season_name) %>%
    group_by(year, source, scaled, variable, Season) %>%
    summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
    ggplot(aes(x = year, y = value, color = source)) +
    geom_point() + 
    geom_line() + 
      geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(title = paste(plot_title, "-", season_name),
         y = y_axis,
         x = "Year",
         color = "Ocean Model") +
    theme_minimal()
}


```

```{r}
MOM6_SummerMLD <- MOM6plot_function_by_season("MLD_0_180","Summer (Jul–Sep)",Scaled_season_MOM6YL_datalong, "Seasonality Distribution of MLD","value" )
```


```{r}
# Create each summer plot
MOM6_SummerMLD <- MOM6plot_function_by_season(
  "MLD_0_180", "Summer (Jul–Sep)", Scaled_season_MOM6YL_datalong,
  "MLD", "value"
)

MOM6_SummerTemp <- MOM6plot_function_by_season(
  "T_0_180", "Summer (Jul–Sep)", Scaled_season_MOM6YL_datalong,
  "Temp", "value"
)

MOM6_SummerXV <- MOM6plot_function_by_season(
  "XV_0_180", "Summer (Jul–Sep)", Scaled_season_MOM6YL_datalong,
  "XV", "value"
)

MOM6_SummerYV <- MOM6plot_function_by_season(
  "YV_0_180", "Summer (Jul–Sep)", Scaled_season_MOM6YL_datalong,
  "YV", "value"
)
```

```{r}

MOM6_SummerMLD <- MOM6_SummerMLD + labs(x = NULL, y = NULL)
MOM6_SummerTemp <- MOM6_SummerTemp + labs(x = NULL, y = NULL)
MOM6_SummerXV <- MOM6_SummerXV + labs(x = NULL, y = NULL)
MOM6_SummerYV <- MOM6_SummerYV + labs(x = NULL, y = NULL)


MOM6_ggarranged_summer <- ggarrange(
  MOM6_SummerMLD,
  MOM6_SummerTemp,
  MOM6_SummerXV,
  MOM6_SummerYV,
  ncol = 2,
  nrow = 2,
  labels = c("A", "B", "C", "D"),
  font.label = list(size = 12, face = "bold"),
  common.legend = TRUE,
  legend = "bottom"
)


MOM6_ggarranged_summer <- annotate_figure(
  MOM6_ggarranged_summer,
  left = text_grob("Value", rot = 90, size = 14, face = "bold"),
  bottom = text_grob("Year", size = 14, face = "bold")
)


print(MOM6_ggarranged_summer)

```


```{r}
MOM6all_seasonal_function("MLD_90_180",Scaled_season_MOM6YL_datalong, "MOM6 Seasonality Distribution of MLD","value" )
```


###Wrangling Monthly GLORYs Data

```{r Bring in Monthly GLORYs Data}
yellowtail_GLORY_monthly.df <- read.csv(
  here("Data","Yellowtail","MonthlyData.csv"))



head(yellowtail_GLORY_monthly.df)
```


```{r Filtering Years & Seaons}


season_GLORY_monthly.df  <- yellowtail_GLORY_monthly.df  %>%
  
filter(year >= 1998 & year <= 2021) %>% ###Matching the GLORY years 
  
 mutate(Season = case_when(
    month %in% 1:3 ~ "Winter",
    month %in% 4:6 ~ "Spring",
    month %in% 7:9 ~ "Summer",
    month %in% 10:12 ~ "Autumn",
    TRUE ~ NA_character_
  ))

head(season_GLORY_monthly.df)

```

```{r}
season_GLORY_monthly.df <- season_GLORY_monthly.df %>%
    mutate(Season = case_when(
      Season == "Winter" ~ "Winter (Jan–Mar)",
      Season == "Spring" ~ "Spring (Apr–Jun)",
      Season == "Summer" ~ "Summer (Jul–Sep)",
      Season == "Autumn" ~ "Autumn (Oct–Dec)",
      TRUE ~ Season
    ))
```


```{r Scaling Monthly GLORY Data}


library(dplyr)
library(tidyr)

Scaled_season_GLORY_monthly.df <- season_GLORY_monthly.df %>%
  group_by(variable, name) %>%
  ungroup() %>%
  mutate(       # overwrite value with scaled version
    source = "GLORY",
    scaled = TRUE,
    Season = case_when(
      month %in% 1:3 ~ "Winter",
      month %in% 4:6 ~ "Spring",
      month %in% 7:9 ~ "Summer",
      month %in% 10:12 ~ "Autumn",
      TRUE ~ NA_character_
    )
  ) %>%
  group_by(variable, newname, Season) %>%
  mutate(scaled_value = scale(value) %>% as.vector()) %>%
  mutate(value=scaled_value)%>%
  select(-scaled_value) %>%         # clean up helper column
  drop_na(value)                    # only remove rows where 'value' is NA



head(Scaled_season_GLORY_monthly.df)




```

```{r}
Scaled_season_GLORY_monthly.df <- Scaled_season_GLORY_monthly.df%>%
    mutate(Season = case_when(
      Season == "Winter" ~ "Winter (Jan–Mar)",
      Season == "Spring" ~ "Spring (Apr–Jun)",
      Season == "Summer" ~ "Summer (Jul–Sep)",
      Season == "Autumn" ~ "Autumn (Oct–Dec)",
      TRUE ~ Season
    ))
```





```{r Make Monthly Unscaled GLORY data long}

Unscaled_season_GLORY_datalong <- season_GLORY_monthly.df %>%

 mutate(
    source = "GLORY",
    scaled = FALSE,
    Season = case_when(
      month %in% 1:3 ~ "Winter (Jan–Mar)",
      month %in% 4:6 ~ "Spring (Apr–Jun)",
      month %in% 7:9 ~ "Summer (Jul–Sep)",
      month %in% 10:12 ~ "Autumn (Oct–Dec)",
      TRUE ~ NA_character_
    )
  )


print(Unscaled_season_GLORY_datalong)
```


```{r Combining Monthly GLORY Datasets}

GLORY_monthlycombined_models <- bind_rows(
  Scaled_season_GLORY_monthly.df,
  Unscaled_season_GLORY_datalong
) %>%
 C,newname, Season, variable, source, scaled) %>%
  summarise(value = mean(value, na.rm = TRUE), .groups = "drop")



head(GLORY_monthlycombined_models)

```

```{r}

GLORYplot_function_by_season <- function(variable_name, season_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(newname == variable_name, Season == season_name) %>%
    group_by(year, Season, newname, source) %>%
    summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
    ggplot(aes(x = year, y = value, color = source)) +
    geom_point() + 
    geom_line() + 
     geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(title = paste(plot_title, "-", season_name),
         y = y_axis,
         x = "Year",
         color = "Ocean Model") +
    theme_minimal()
}

```



```{r}
GLORYplot_function_by_season("MLD_0_180","Summer (Jul–Sep)",Scaled_season_GLORY_monthly.df, "Seasonality Distribution of MLD","value" )
```

```{r}
# Create each summer plot
GLORY_SummerMLD <- GLORYplot_function_by_season(
  "MLD_0_180", "Summer (Jul–Sep)", Scaled_season_GLORY_monthly.df,
  "MLD", "value"
)

GLORY_SummerTemp <- GLORYplot_function_by_season(
  "T_0_180", "Summer (Jul–Sep)", Scaled_season_GLORY_monthly.df,
  "Temp", "value"
)

GLORY_SummerXV <- GLORYplot_function_by_season(
  "XV_0_180", "Summer (Jul–Sep)",Scaled_season_GLORY_monthly.df,
  "XV", "value"
)

GLORY_SummerYV <- GLORYplot_function_by_season(
  "YV_0_180", "Summer (Jul–Sep)", Scaled_season_GLORY_monthly.df,
  "YV", "value"
)
```




```{r}
library(ggpubr)

GLORY_SummerMLD <- GLORY_SummerMLD + labs(x = NULL, y = NULL) 
GLORY_SummerTemp <- GLORY_SummerTemp + labs(x = NULL, y = NULL)
GLORY_SummerXV <- GLORY_SummerXV + labs(x = NULL, y = NULL)
GLORY_SummerYV <- GLORY_SummerYV + labs(x = NULL, y = NULL)

GLORY_ggarranged_summer <- ggarrange(
  GLORY_SummerMLD,
  GLORY_SummerTemp,
  GLORY_SummerXV,
  GLORY_SummerYV,
  ncol = 2,
  nrow = 2,
  labels = c("A", "B", "C", "D"),
  font.label = list(size = 12, face = "bold"),
  common.legend = TRUE,
  legend = "bottom"
)


GLORY_ggarranged_summer <- annotate_figure(
  GLORY_ggarranged_summer,
  left = text_grob("Value", rot = 90, size = 14, face = "bold"),
  bottom = text_grob("Year", size = 14, face = "bold")
)


print(GLORY_ggarranged_summer)


```

```{r}

summer_combined_side_by_side <- ggarrange(
  GLORY_SummerMLD, MOM6_SummerMLD,
  GLORY_SummerTemp, MOM6_SummerTemp,
  GLORY_SummerXV, MOM6_SummerXV,
  GLORY_SummerYV, MOM6_SummerYV,
  ncol = 2, nrow = 4,
  labels = c("A", "B", "C", "D", "E", "F", "G", "H"),
  font.label = list(size = 12, face = "bold"),
  common.legend = TRUE,
  legend = "bottom"
)


summer_combined_side_by_side <- annotate_figure(
  summer_combined_side_by_side,
  left = text_grob("Value", rot = 90, size = 14, face = "bold"),
  bottom = text_grob("Year", size = 14, face = "bold")
)

print(summer_combined_side_by_side)

```
```{r}

###renaming MOM6 variable column to match GLORY column

Scaled_season_MOM6YL_datalong <- Scaled_season_MOM6YL_datalong %>%
  rename(
    newname = variable
  )
```


```{r}
Season_combined.df <- bind_rows(Scaled_season_MOM6YL_datalong, Scaled_season_GLORY_monthly.df )

head(Season_combined.df)
```


```{r}
GLORYplot_function_by_season("MLD_0_180","Summer (Jul–Sep)",Season_combined.df, "Seasonality Distribution of MLD","value" )
```



```{r Summer MLD 0_180 Plots}


Combined_SummerMLD <- GLORYplot_function_by_season(
  "MLD_0_180", "Summer (Jul–Sep)", Season_combined.df,
  "MLD", "value"
)

Combined_SummerTemp <- GLORYplot_function_by_season(
  "T_0_180", "Summer (Jul–Sep)", Season_combined.df,
  "Temp", "value"
)

Combined_SummerXV <- GLORYplot_function_by_season(
  "XV_0_180", "Summer (Jul–Sep)",Season_combined.df,
  "XV", "value"
)

Combined_SummerYV <- GLORYplot_function_by_season(
  "YV_0_180", "Summer (Jul–Sep)", Season_combined.df,
  "YV", "value"
)
```


```{r}

# Add axis labels to each Combined plot
Combined_SummerMLD <- Combined_SummerMLD + labs(x = NULL, y = NULL)
Combined_SummerTemp <- Combined_SummerTemp + labs(x = NULL, y = NULL)
Combined_SummerXV <- Combined_SummerXV + labs(x = NULL, y = NULL)
Combined_SummerYV <- Combined_SummerYV + labs(x = NULL, y = NULL)

# Arrange the plots in a 2x2 grid with labels and shared legend
GLORY_ggarranged_summer <- ggarrange(
  Combined_SummerMLD,
  Combined_SummerTemp,
  Combined_SummerXV,
  Combined_SummerYV,
  ncol = 2,
  nrow = 2,
  labels = c("A", "B", "C", "D"),
  font.label = list(size = 12, face = "bold"),
  common.legend = TRUE,
  legend = "bottom"
)

# Annotate the full figure with axis titles
GLORY_ggarranged_summer <- annotate_figure(
  GLORY_ggarranged_summer,
  left = text_grob("Value", rot = 90, size = 14, face = "bold"),
  bottom = text_grob("Year", size = 14, face = "bold")
)

# Display the arranged and annotated plot
print(GLORY_ggarranged_summer)
```


```{r GLORY All Season Plot Function}

GLORYall_seasonal_function <- function(variable_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(newname == variable_name) %>%
    group_by(year, Season, name) %>%
    summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
    ggplot(aes(x = year, y = value, color = Season)) +
    geom_point() +
    geom_line() +
  geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    facet_wrap(~ name, scales = "free_y") +  # Facet by name to see all in one plot
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(title = plot_title,
         y = y_axis,
         x = "Year",
         color = "Season") +
    theme_minimal()
}


```

```{r}
GLORYall_seasonal_function("MLD_0_180", Scaled_season_GLORY_monthly.df, "GLORY Seasonality Distribution of MLD","value" )
```

```{r All Season Plot Function}

MOM6all_seasonal_function2 <- function(variable_name, dataframe, plot_title, y_axis) {
  
  dataframe %>%
    filter(newname == variable_name) %>%
    group_by(year, Season, newname, scaled, source) %>%
    summarise(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
    ggplot(aes(x = year, y = value, color = Season)) +
    geom_point() +  
    geom_hline(yintercept = 0, color = "darkblue", linetype = 3, linewidth = 1) +
    geom_line() + 
    scale_x_continuous(breaks = seq(min(dataframe$year), max(dataframe$year), by = 5)) +
    labs(title = plot_title,
         y = y_axis,
         x = "Year",
         color = "Season") +
    theme_minimal()
}



###Take means of each season so it plots mean of each season over each year
```


```{r}


library(patchwork)


p1 <- MOM6all_seasonal_function2("MLD_0_180", Scaled_season_MOM6YL_datalong, 
                                "MOM6 Seasonality Distribution of MLD", "value") +
  theme(legend.position = "none")  

p2 <- GLORYall_seasonal_function("MLD_0_180", Scaled_season_GLORY_monthly.df, 
                                 "GLORY Seasonality Distribution of MLD", "value")


combined <- (p1 / p2) + plot_layout(guides = "collect") & theme(legend.position = "right")

print(combined)


ggsave(
  filename = "seasonal_MLD_comparison.png",
  plot     = combined,
  width    = 12,
  height   = 6,
  dpi      = 300)




```








###GAMS Model

```{r Pull in recruitment data}

Recruitment_Yellow_Tail.df <- read.csv(
  here("Data", "Yellowtail", "RecruitmentDeviationsYellowtail2025.csv")
) %>%
  rename(
    year = Yr,
    Y_rec = Value
  )

print(Recruitment_Yellow_Tail.df)


```

```{r}

# Remove NA rows from both data frames
Full_Glory_Yellow_Tail.df <- na.omit(Full_Glory_Yellow_Tail.df)
Full_MOM6_Yellow_Tail.df <- na.omit(Full_MOM6_Yellow_Tail.df)

```


```{r Temp Covariance}
#this tells us the covariance
cov1<- cov(Full_Glory_Yellow_Tail.df%>%filter(source=="GLORY")%>%select(Tcop),
Full_MOM6_Yellow_Tail.df%>%filter(source=="MOM6")%>%select(Tcop))



cov2<- cov(Full_Glory_Yellow_Tail.df%>%filter(source=="GLORY")%>%select(Tpart),
Full_MOM6_Yellow_Tail.df%>%filter(source=="MOM6")%>%select(Tpart))

```

```{r Temp Correlation}
#this tells us the Correlation
cor1<- cor(Full_Glory_Yellow_Tail.df%>%filter(source=="GLORY")%>%select(Tcop),
Full_MOM6_Yellow_Tail.df%>%filter(source=="MOM6")%>%select(Tcop))



cor2<- cor(Full_Glory_Yellow_Tail.df%>%filter(source=="GLORY")%>%select(Tpart),
Full_MOM6_Yellow_Tail.df%>%filter(source=="MOM6")%>%select(Tpart))

# Create data frame with named covariates
results_df <- data.frame(
  covariate = c("Tcop", "Tpart"),
  covariance = c(cov1, cov2),
  correlation = c(cor1, cor2)
)

print(results_df)


```



```{r Combiing wide MOM6 data and Recruitment Data}

MOM6_Rec_Yellow_Tail.df <- left_join(
  Scaled_MOM6YL_datalong,
  Recruitment_Yellow_Tail.df,
  by = "year"
)

print(MOM6_Rec_Yellow_Tail.df)


```


```{r Combiing wide GLORY data and Recruitment Data}

GLORY_Rec_Yellow_Tail.df <- left_join(
  Scaled_GYL_datalong,
  Recruitment_Yellow_Tail.df,
  by = "year"
)

print(GLORY_Rec_Yellow_Tail.df)


```




```{r}
LongScaled_CombinedModels_Rec_Yellow_Tail.df <- left_join(
  Scaled_combined_models,
  Recruitment_Yellow_Tail.df,
  by = "year"
)

print(LongScaled_CombinedModels_Rec_Yellow_Tail.df)
```



```{r}

#the function starts here
gamoutput<-function(modelname, covariate, data){
  
#this is the equation of the gam that filters the for a model (GLORYs or MOM6)
# and filters for a covariate (MLDpjuv, Tcop etc. etc.)
gamfit<- gam(Y_rec~s(value,k=3), data=data%>%filter(source == modelname, variable==covariate), method = "REML") 

###Do I need to change the name of model name to "Glory" or "MOM6"

summary <- summary(gamfit) #this pulls out the summary of the model

#this pulls out the model preditions and the SEs of the predictions and stores
#them into a dataframe

predictions <- data.frame(prediction=predict(gamfit, se.fit=TRUE),year=unique(data$year))%>%
  mutate(variable=covariate, source = modelname) 

#pulling out the values we need from the summary and adding to a dataframe
#that we can easily make a table out of
results <- data.frame(covariate=covariate, Model = modelname, pvalue = summary$s.table[, "p-value"], DevianceExp = summary$dev.expl, rsq = summary$dev.expl)

#pulling out the shape of the relationship so that we can plot it!
smooth_data <- smooth_estimates(gamfit)%>%  # Or specify the smooth term you want to plot
  add_constant(model_constant(gamfit)) %>% # Add the intercept
  add_confint()%>% # Add the credible interval
 # pivot_longer(c(covariate),names_to = "Smooth",values_to ="Value")%>%
  select(-c(.by))%>%
  mutate(covariate=covariate, Model = modelname)

#putting it together as a list so we can get a single output with all the great 
#info that we need!

output<-list(summary, predictions, results,smooth_data)
return(output)
}

```


```{r}
Modelnames <- unique(LongScaled_CombinedModels_Rec_Yellow_Tail.df$source) #change this to your dataset
covariatenames <- unique(LongScaled_CombinedModels_Rec_Yellow_Tail.df$variable) #change this to your dataset
predictions_gam<- data.frame()
results_gam<- data.frame()
smooths_gam<- data.frame()

for(i in 1:length(covariatenames)){
  for(j in 1:length(Modelnames)){
    gamout<-gamoutput(Modelnames[j], covariatenames[j], LongScaled_CombinedModels_Rec_Yellow_Tail.df)
    predictions_gam<-rbind(predictions_gam, gamout[[2]])
    results_gam<-rbind(results_gam, gamout[[3]])
    smooths_gam<-rbind(smooths_gam, gamout[[4]])
  }
  print(i)
}
```


```{r}

#change the code here to have your dataset long name, and you will create a 
#multi panel plot showing the relationships of both models on the plot! We can
#also add the deviance explained to the plot as well :)

smooth_full<- smooths_gam%>%left_join(LongScaled_CombinedModels_Rec_Yellow_Tail.df)%>%left_join(results_gam)

partial_effects<-ggplot(smooths_gam) +  # Setup the plot with the fitted values
  facet_grid(~covariate)+
  geom_line(aes(x = value, y = .estimate, col=Model), lwd=1.25) + # Add estimated smooth
    geom_point(data = LongScaled_CombinedModels_Rec_Yellow_Tail.df%>%rename(covariate=variable), aes(x = value, y = Y_rec, col=source),alpha = 0.2) + # Add your data points
# Diandre', I couldnt figure out how to do this in one call sot there are
# multiple geom text calls, which means you will 
# have to change the model filter!! and potentially the x and y values
  geom_text(
  data    = results_gam%>%filter(Model=="MOM6"),
  mapping = aes(x = -2, y = 5, label = round(DevianceExp,2), group=covariate),
  hjust   = -0.1,
  vjust   = -1, col='#F8766D'
)+
    geom_text(
  data    = results_gam%>%filter(Model=="GLORYs"),
  mapping = aes(x = -2, y = 3, label = round(DevianceExp,2), group=covariate),
  hjust   = -0.1,
  vjust   = -1, col='#00BFC4'
)+
annotate("text", x= -1, y = 8,label="Dev Explained")+
  guides(text="none")+
  theme_bw()
partial_effects 
```









































